/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.11 scene.gltf
Author: nkbergen (https://sketchfab.com/nkbergen)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/bunny-ee92171e643641c8b9d49059ce87b60c
Title: Bunny
*/

import React, { useLayoutEffect, useRef } from 'react'
import { useGLTF, useScroll } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'
import { gsap } from 'gsap'

export function Bunny(props) {
  const { nodes, materials } = useGLTF('./models/bunny/scene.gltf')
  const bunnyRef = useRef()
  const scroll = useScroll();
  const tl = useRef()

  useFrame((state, delta) => {
    tl.current.seek(scroll.offset * tl.current.duration())
  })

  useLayoutEffect(() => {
    tl.current = gsap.timeline({defaults: {duration: 2, ease: 'power1.inOut'}})
    console.log("ref", bunnyRef.current)
    console.log("timeline", tl)

    tl.current
    .to(bunnyRef.current.rotation, {y: -1}, 2)
    .to(bunnyRef.current.position, {x: 1}, 2)

    .to(bunnyRef.current.rotation, {y: 1}, 6)   
    .to(bunnyRef.current.position, {x: -1}, 6)

    .to(bunnyRef.current.rotation, {y: 0}, 11)
    .to(bunnyRef.current.rotation, {x: 1}, 11)
    .to(bunnyRef.current.position, {x: 0}, 11)

    .to(bunnyRef.current.rotation, {y: 0}, 13)
    .to(bunnyRef.current.rotation, {x: -1}, 13)    
    .to(bunnyRef.current.position, {x: 0}, 13)

    .to(bunnyRef.current.rotation, {y: 0}, 16)   
    .to(bunnyRef.current.rotation, {x: 0}, 16) 
    .to(bunnyRef.current.position, {x: 0}, 16)    

    .to(bunnyRef.current.rotation, {y: 0}, 20)   
    .to(bunnyRef.current.rotation, {x: 0}, 20) 
    .to(bunnyRef.current.position, {x: 0}, 20)   
  }, [])

  return (
    <group {...props} dispose={null} ref={bunnyRef}>
      <mesh geometry={nodes.Object_3.geometry} material={materials['Scene_-_Root']} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('./models/bunny/scene.gltf')
